from flask import Blueprint, request ,jsonify
from services.ResultService import ResultService
import logging
from io import BytesIO
from reportlab.pdfgen import canvas
from flask import send_file

logger = logging.getLogger(__name__)
result_bp = Blueprint('result', __name__)

@result_bp.route('/api/generateReport', methods=['GET'])
def generateReport():
    logger.debug("Generate Report API CALLED")
    machine_id = request.args.get('machine_id')
    
    logger.debug("Machine id is: ", machine_id)
    result = ResultService.get_machine_info(machine_id)
    if result:
        logger.debug(f"Machine Information: {result.machine_id}")
    else:
        logger.debug(f"No machine found for ID: {machine_id}")

    logger.debug("Machine Information: ", result.machine_id)
    if not result:
        return jsonify({"error": "Machine not found"}), 404
    
    buffer = BytesIO()  
    pdf = canvas.Canvas(buffer)
    
    pdf.setTitle(f"Machine Report - {result.machine_id}")
    pdf.drawString(100, 800, f"Machine Report for {result.machine_id}")
    pdf.drawString(100, 780, f"Machine ID: {result.result_id}")
    pdf.drawString(100, 760, f"Total Strips Evaluated: {result.total_strips}")
    pdf.drawString(100, 740, f"Defective Strips: {result.non_faulty_strips}")
    pdf.drawString(100, 720, f"Non-Defective Strips: {result.faulty_strips}")
    pdf.drawString(100, 50, "Generated by Machine Inspection System")
    pdf.showPage()
    pdf.save()
    buffer.seek(0)

    return send_file(buffer, as_attachment=True, download_name=f"Machine_Report_{machine_id}.pdf", mimetype='application/pdf')