from flask import Blueprint, request ,jsonify, session
from services.ResultService import ResultService
import logging
from models.users import User
from io import BytesIO
from reportlab.pdfgen import canvas
from flask import send_file, Flask

logger = logging.getLogger(__name__)
result_bp = Blueprint('result', __name__)
user_bp = Blueprint('user', __name__)


@result_bp.route('/api/totalStrips', methods=['GET'])
def totalStrips():
    logger.debug("Get Results API CALLED")
    print("Session in getResults:", dict(session))
    current_user_id = session.get('user_id') 
    print("Session user_id in getResults:", 1)
    
    results = ResultService.get_total_medicinal_strips(current_user_id)
    print("Results in getResults:", results)

    
    return jsonify(results), 200

@result_bp.route('/api/faultyStrips', methods=['GET'])
def faultyStrips():
    current_user_id = session.get('user_id') 

    results = ResultService.get_faulty_strips(current_user_id)
    print("Results in getResults:", results)
    return jsonify(results), 200

@result_bp.route('/api/nonFaultyStrips', methods=['GET'])
def nonfaultyStrips():
    current_user_id = session.get('user_id') 

    results = ResultService.get_non_faulty_strips(current_user_id)
    print("Results in getResults:", results)
    return jsonify(results), 200

@result_bp.route('/api/generateReport', methods=['GET'])
def generateReport():
    logger.debug("Generate Report API CALLED")
    machine_id = request.args.get('machine_id')
    
    logger.debug("Machine id is: ", machine_id)
    result = ResultService.get_machine_info(machine_id)
    if result:
        logger.debug(f"Machine Information: {result.machine_id}")
    else:
        logger.debug(f"No machine found for ID: {machine_id}")

    logger.debug("Machine Information: ", result.machine_id)
    if not result: 
        return jsonify({"error": "Machine not found"}), 404
    
    buffer = BytesIO()  
    pdf = canvas.Canvas(buffer)
    
    pdf.setTitle(f"Machine Report - {result.machine_id}")
    pdf.drawString(100, 800, f"Machine Report for {result.machine_id}")
    pdf.drawString(100, 780, f"Machine ID: {result.result_id}")
    pdf.drawString(100, 760, f"Total Strips Evaluated: {result.total_strips}")
    pdf.drawString(100, 740, f"Defective Strips: {result.non_faulty_strips}")
    pdf.drawString(100, 720, f"Non-Defective Strips: {result.faulty_strips}")
    pdf.drawString(100, 50, "Generated by Machine Inspection System")
    pdf.showPage()
    pdf.save()
    buffer.seek(0)
    
    return send_file(buffer, as_attachment=True, download_name=f"Machine_Report_{machine_id}.pdf", mimetype='application/pdf')

