"""Fix migration

Revision ID: 22a2a592e633
Revises: 4116c346fb65
Create Date: 2025-01-29 15:14:07.985631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a2a592e633'
down_revision = '4116c346fb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('machine_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('machine_profile_img', sa.String(length=255), nullable=True))
    op.execute("UPDATE machine SET machine_name = 'Unnamed Machine' WHERE machine_name IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('machine_profile_img')
        batch_op.drop_column('machine_description')
        batch_op.drop_column('machine_name')

    # ### end Alembic commands ###
