"""Machine Table new entries

Revision ID: 64aa13839664
Revises: 6171bddf4494
Create Date: 2025-01-29 10:52:45.792297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64aa13839664'
down_revision = '6171bddf4494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('machine_profile_img', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('machine_profile_img')
        batch_op.drop_column('machine_description')

    # ### end Alembic commands ###
