"""Fix migrationss

Revision ID: 93da512342d2
Revises: 22a2a592e633
Create Date: 2025-01-29 15:23:53.119287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93da512342d2'
down_revision = '22a2a592e633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('machine_profile_img', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('machine_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('machine_name')
        batch_op.drop_column('machine_profile_img')
        batch_op.drop_column('machine_description')

    # ### end Alembic commands ###
