"""Fix migrationsss

Revision ID: d110df788f9f
Revises: 93da512342d2
Create Date: 2025-01-29 15:27:15.415853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd110df788f9f'
down_revision = '93da512342d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('machine_profile_img', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('machine_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('machine_name')
        batch_op.drop_column('machine_profile_img')
        batch_op.drop_column('machine_description')

    # ### end Alembic commands ###
